### ISSUE TITLE
Why label_colors in .labelmerc not work in linux

### ISSUE THREAD

**Issue by shunmian** [wkentaro/labelme#1338]
### Provide environment information

/home/miniconda3/envs/labelme/bin/python
Python 3.12.0
labelme         5.2.1

### What OS are you using?

ubuntu 20.04

### Describe the Bug

I have added 
```
label_colors: {
  '1': [255,0,0],
  '2': [0,0,255]
}
```
to .labelmerc for customize label color assignment as suggested by [issue 712][https://github.com/wkentaro/labelme/issues/712].
But it doesn't work, the labelme shows all green color for every label. Any guidance?

**Comment by sc0v1n0** [comment]
Good evening @shunmian, to be able to change the colors you will have to change more than one parameter in the .labelmerc file.

```yaml
flags: null
label_flags: null
labels: [AB, BC, CD]
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: manual  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: {AB: [255,21,0], BC: [12,23,255], CD: [12,225,125]}

```

labels: Define the labels
shape_color: Change auto to manual, if not another color will be defined.
label_colors: Then you pass the dictionary with the name of the label defined in the previous variable 'labels', then define the colors.

![image](https://github.com/wkentaro/labelme/assets/56802572/04c5a5da-82c5-4718-a1c6-ca54a6ffe358)

config:

![image](https://github.com/wkentaro/labelme/assets/56802572/1c22815f-70ac-4c5e-95dc-1fd5a1437143)


Also note that labelme supports these Python versions.
![image](https://github.com/wkentaro/labelme/assets/56802572/724ba9ff-8022-4a26-9eb2-5ad7a7af8869)

**Comment by wkentaro** [comment]
> *This was generated by AI during triage.*

Re-triaged following @sc0v0ne's 2023-10-17 reply, which was never confirmed.

## Triage Notes

**What we've established so far:**

- @sc0v0ne's answer is very likely the resolution: `label_colors` on its own does nothing. It is only consulted when `shape_color` is set to `manual`. The default is `shape_color: auto`, under which colors come from the built-in colormap indexed by label order and `label_colors` is ignored entirely.
- Confirmed against current `main`: the color-resolution path takes the colormap branch when `shape_color` is `auto` and never reads `label_colors`; it reads `label_colors` only on the `manual` branch, falling back to `default_shape_color` (which is `[0, 255, 0]`, green) when a label has no entry. That matches the all-green rendering you described.
- There is no OS-specific code anywhere in this path. Config file resolution, YAML parsing, and color computation are identical on Linux and macOS, so "works on macOS but not Ubuntu" is much more likely to be two different `~/.labelmerc` files (or two environments reading different ones) than a platform bug.
- A working configuration looks like:
  ```yaml
  shape_color: manual
  default_shape_color: [0, 255, 0]
  label_colors:
    "1": [255, 0, 0]
    "2": [0, 0, 255]
  ```
- Note the label keys must match your label strings exactly; a label with no entry falls back to `default_shape_color` rather than erroring.

**What we still need from you (@shunmian):**

- Does adding `shape_color: manual` to your Ubuntu `~/.labelmerc` fix it? This is the single question blocking this issue.
- If it does not: please paste your full Ubuntu `~/.labelmerc` (not just the `label_colors` block) and the output of `python -c "import pathlib; print(pathlib.Path('~/.labelmerc').expanduser().read_text())"`, so we can confirm the file labelme actually reads is the one you edited.
- Please also confirm whether your macOS `~/.labelmerc` differs from the Ubuntu one, and how.

Without a reply this will be treated as answered by the configuration above.
